source 'https://rubygems.org'

gem 'pg', '~> 1.3', '>= 1.3.4'
gem 'activerecord'
gem 'sinatra'
gem 'puma'
gem 'byebug'
gem 'activesupport', '~> 5.0', '>= 5.0.0.1'

gem 'sinatra-activerecord'
gem 'rake'


group :test do

  gem 'rspec'
  gem 'rack-test'
end